# Generated by Django 3.2 on 2024-07-12 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='recite',
            new_name='recipe',
        ),
    ]
